// angular/src/app/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';
import * as CONSTANT from '../constant'

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent implements OnInit {
  paths: any[] = [];

  constructor() {
    for (let i in CONSTANT.PATHS)
      this.paths.push(CONSTANT.PATHS[i])
  }

  ngOnInit(): void {
  }

}

<footer class="footer">
  <div class="content has-text-centered">
    <p>
      <strong>Azwraith.me</strong> by <a href="https://github.com/wchr-aun">wchr-aun</a> | <i class="fas fa-code"></i> Source code
    </p>
  </div>
</footer>

// src/components/Footer.vue
<template>
  <footer class="has-background-grey-dark">
    <div class="content has-text-centered has-text-white-ter subtitle is-6">
      <p>Published: <a href="https://github.com/anaunz" class="has-text-white-ter">anaunz</a> | 
      <i class="fas fa-copyright"></i> 2018 <router-link to="/" class="has-text-white-ter">Azwraith.me</router-link> | 
      <i class="fas fa-address-book"></i> Contact: wchr.aun@gmail.com
      </p>
    </div>
  </footer>
</template>

<style>
footer{
  padding-block-start: 20px;
  padding-block-end: 15px;
}
</style>
